### ISSUE TITLE
[FEATURE] 希望可以增加可设置快捷键的功能

### ISSUE THREAD

**Issue by 3CB3EC** [jiang-taibai/LiteLoaderQQNT-Quickly-Remove-Conversations#3]
感觉这个插件非常的实用，但对我来说按按鼠标中键/按滚轮比较不习惯，希望可以将其设置为其他键（最好是键盘上的按键），谢谢！

**Comment by jiang-taibai** [comment]
感谢您的支持与建议，现已发布的 [release-v1.1.0](https://github.com/jiang-taibai/LiteLoaderQQNT-Quickly-Remove-Conversations/releases/tag/v1.1.0) 版本中提供了四种键盘按键+三种鼠标按键的组合快捷键功能。
