### ISSUE TITLE
[BUG] Title按动滚轮移除会话后，光标为滚动模式，需要再按一次滚轮方可恢复

### ISSUE THREAD

**Issue by san-ren** [jiang-taibai/LiteLoaderQQNT-Quickly-Remove-Conversations#4]
不知道是我自己的问题，还是大家都这样

默认的是按动滚轮，我没改

按动滚轮移除会话后，光标为滚动模式，需要再按一次滚轮方可恢复

就像word里按动滚轮后，光标变换，轻微移动就可快速翻页，我也不知道叫啥，就叫滚动模式吧

如今这样，不能保持为一般情况下的箭头显示，并没有方便什么😁

**Comment by jiang-taibai** [comment]
谢谢反馈，刚刚测试了一下，确实存在此问题，你可以暂时使用其他快捷键，后面将修复此问题

**Comment by san-ren** [comment]
> 谢谢反馈，刚刚测试了一下，确实存在此问题，你可以暂时使用其他快捷键，后面将修复此问题

感谢开发
