### ISSUE TITLE
分享，鼠标中键移除会话的 js 脚本

### ISSUE THREAD

**Issue by san-ren** [jiang-taibai/LiteLoaderQQNT-Quickly-Remove-Conversations#6]
觅到平替，分享出来。功能正常，可以放心使用

https://github.com/Natsukage/Scriptio-user-scripts/blob/main/ConversationQuickRemover.js

需要搭配[Scriptio](https://github.com/PRO-2684/Scriptio)

予大众方便，为作者减负😁

**Comment by jiang-taibai** [comment]
谢谢分享，最近一个月特别忙，没有时间维护还请见谅，现已发布新版本解决了该问题，希望能帮到你
